#!/bin/bash

# this one doesn't work for some reason
#. /usr/local/tools/dotkit/init
#use cudatoolkit-5.0

#. /usr/share/Modules/init/sh
#module load cudatoolkit/5.0

set -x

# build autotools that we need (one of the patches below changes configure)
pushd autotools
  ./buildme
popd

# add autotools install bin to our path
export PATH=`pwd`/autotools/install/bin:$PATH

# unzip mvapich source
rm -rf mvapich2-1.9
tar -zxf mvapich2-1.9.tgz

# apply patches
patch -p1 < 0001-specify-path-to-pmgr-pmi.patch
patch -p1 < 0001-drop-network-libs-from-wrapper.patch
patch -p1 < 0001-do-not-read-user-config-if-home-is-not-set.patch

# build MPI
cd mvapich2-1.9

# MPI installation directory
installdir=`pwd`/install

# GNU compiler settings
#export CC=gcc 
#export CXX=g++ 
#export F77=gfortran
#export FC=gfortran
#export MPICHLIB_CFLAGS="-g -O2"
#export MPICHLIB_CXXFLAGS="-g -O2"
#export MPICHLIB_FFLAGS="-g -O2 -fno-second-underscore"
#export MPICHLIB_FCFLAGS="-g -O2 -fno-second-underscore"

# Intel compiler settings
export CC=icc 
export CXX=icpc
export F77=ifort
export FC=ifort
export MPICHLIB_CFLAGS="-g -O2"
export MPICHLIB_CXXFLAGS="-g -O2"
export MPICHLIB_FFLAGS="-g -O2"
export MPICHLIB_FCFLAGS="-g -O2"

# PGI compiler settings
#export CC=pgcc 
#export CXX=pgCC
#export F77=pgf77
##export FC=pgf90
#export MPICHLIB_CFLAGS="-g -O2 -fPIC"
#export MPICHLIB_CXXFLAGS="-g -O2 -fPIC"
#export MPICHLIB_FFLAGS="-g -O2 -fPIC"
#export MPICHLIB_FCFLAGS="-g -O2 -fPIC"

# Pathscale compiler settings
#export CC=pathcc 
#export CXX=pathCC
#export F77=pathf90
##export FC=pathf90
#export MPICHLIB_CFLAGS="-g -O2"
#export MPICHLIB_CXXFLAGS="-g -O2"
#export MPICHLIB_FFLAGS="-g -O2 -fno-second-underscore"
#export MPICHLIB_FCFLAGS="-g -O2 -fno-second-underscore"

export CONFIG_FLAGS="--enable-fast=all --enable-g=dbg --enable-nmpi-as-mpi"

# PMI library:  PMGR_COLLECTIVE, SLURM
#export PMI="--with-pm=no --with-pmi=pmgr --with-pmgr=/usr/local/tools/pmgr"
export PMI="--with-pm=no --with-pmi=slurm"

# Network devices:  PSM, Mellanox, Shared Memory, Mellanox + CUDA
export DEVICE_FLAGS="--with-device=ch3:psm"
#export DEVICE_FLAGS="--with-device=ch3:mrail --with-rdma=gen2"
#export DEVICE_FLAGS="--with-device=ch3:mrail --with-rdma=gen2 --enable-cuda --with-cuda=/opt/cudatoolkit-5.0"
#export DEVICE_FLAGS="--with-device=ch3:nemesis"

# needed for make dist step
#export YACC="/usr/bin/bison"

# we have to do this to rebuild configure to include pmgr
./autogen.sh

./configure \
  --prefix=${installdir} \
  --enable-f77 --enable-fc --enable-cxx \
  ${CONFIG_FLAGS} \
  --enable-shared --enable-sharedlibs=gcc \
  --enable-debuginfo \
  ${PMI} \
  ${DEVICE_FLAGS} \
  --enable-romio --with-file-system=lustre+nfs+ufs \
  --disable-mpe --without-mpe

make clean

make -j8 VERBOSE=1

make install VERBOSE=1
